app/urls.py
from django.urls import path
from django.contrib import admin
from .views import HomeView, AboutView, TransformationView, ContactView, PackagesView, QuestionnaireView, FoodView
from django.views.decorators.csrf import csrf_exempt


urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('about-us/', AboutView.as_view(), name='about-us'),
    path('transformation/', TransformationView.as_view(), name='transformation'),
    path('packages/', PackagesView.as_view(), name='packages'),
    path('contact/', ContactView.as_view(), name='contact'),
    path('questionnaire/', csrf_exempt(QuestionnaireView.as_view()), name='questionnaire'),
    path('food/', FoodView.as_view(), name='food'),

]


admin.site.site_header = 'Hawary Fitness Trainer'
admin.site.index_title = 'Main Page'
admin.site.site_title = 'Hawary admin'

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns


urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('i18n/', include('django.conf.urls.i18n')),
                  path('', include('app.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# urlpatterns += i18n_patterns(
#     path('', include('app.urls')),
# ) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/models.py
from django.db import models
from cloudinary.models import CloudinaryField


class BaseModel(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class PackageGroup(BaseModel):
    name = models.CharField(max_length=255)
    name_ar = models.CharField(max_length=255)
    description = models.CharField(max_length=255)
    description_ar = models.CharField(max_length=255)
    img = CloudinaryField('image')

    def __str__(self):
        return self.name


class Package(BaseModel):
    name = models.CharField(max_length=255)
    name_ar = models.CharField(max_length=255)
    price = models.IntegerField()
    price_ar = models.IntegerField()
    description = models.CharField(max_length=255)
    description_ar = models.CharField(max_length=255)
    package = models.ForeignKey('PackageGroup', on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class PackageDetails(BaseModel):
    description = models.CharField(max_length=255)
    description_ar = models.CharField(max_length=255)
    package_details = models.ForeignKey('Package', on_delete=models.CASCADE, related_name='package_details')


class GreatTransformation(BaseModel):
    name = models.CharField(max_length=255)
    name_ar = models.CharField(max_length=255)
    img = CloudinaryField('image')

    def __str__(self):
        return self.name


class GreatTransformationDetails(BaseModel):
    description = models.CharField(max_length=255)
    description_ar = models.CharField(max_length=255)
    trans_details = models.ForeignKey('GreatTransformation', on_delete=models.CASCADE, related_name='trans_details')


class Setting(BaseModel):
    # address = models.CharField(max_length=255)
    # main_mobile_number = models.CharField(max_length=255)
    # secondary_mobile_number = models.CharField(max_length=255)
    # email = models.EmailField()
    about_us = models.TextField(max_length=8000)
    about_us_ar = models.TextField(max_length=8000)
    # about_us_img = CloudinaryField('image')

    def __str__(self):
        return self.about_us


class Slider(BaseModel):
    img = CloudinaryField('image')
    title = models.CharField(max_length=255)
    title_ar = models.CharField(max_length=255)
    description = models.CharField(max_length=255)
    description_ar = models.CharField(max_length=255)
    setting = models.ForeignKey('Setting', on_delete=models.CASCADE, related_name='slider')


class Transformation(BaseModel):
    name = models.CharField(max_length=255)
    name_ar = models.CharField(max_length=255)
    title = models.CharField(max_length=500)
    title_ar = models.CharField(max_length=500)
    description = models.TextField(max_length=500)
    description_ar = models.TextField(max_length=500)
    order = models.IntegerField(unique=True)
    img = CloudinaryField('image')

    def __str__(self):
        return self.title


class FoodPackages(BaseModel):
    name = models.CharField(max_length=255)
    name_ar = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class FoodRaw(BaseModel):
    FoodPackages = models.ForeignKey('FoodPackages', on_delete=models.CASCADE, related_name='Food_packages')


class Food(BaseModel):
    name = models.CharField(max_length=255)
    name_ar = models.CharField(max_length=255)
    food_raw = models.ForeignKey('FoodRaw', on_delete=models.CASCADE, related_name='food_raw')

    def __str__(self):
        return self.name

templates/about-us.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}

  {% block content %}
    <!-- Breadcrumb Section Begin -->
    <section class="breadcrumb-section set-bg" data-setbg="{% static 'img/abot-bread.jpeg' %}">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <div class="breadcrumb-text">
<!--                        <h2>About us</h2>-->
                        <div class="bt-option">
<!--                            <span>{% trans 'Make You Best' %}</span>-->
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Breadcrumb Section End -->
        <!-- About US Section Begin -->
        <section class="contact-section  new-bg-color ">
            <div class="container-fluid">
                <div class="row">
<!--                    <div class="col-lg-6 p-0">-->
<!--                        <div class="about-video set-bg" data-setbg="{{ setting.about_us_img.url }}">-->
<!--                        </div>-->

<!--                    </div>-->
                    <div class="col-lg-12 p-0">
                        <div id="new-about-text" class="about-text pg-ground">
                            <div class="section-title">
<!--                                <span>About Us</span>-->
                            </div>
                            <div class="at-desc">
                                {% get_current_language as LANGUAGE_CODE %}
                                {% if  LANGUAGE_CODE == 'ar'%}
                                <p>{{ setting.about_us_ar }}</p>
                                {% else %}
                                <p>{{ setting.about_us }}</p>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </section>
        <!-- About US Section End -->


{% endblock %}

templates/base.html
{% load static %}
{% load i18n %}

<!DOCTYPE html>
<html lang="zxx">

<head>
    <meta charset="UTF-8">
    <meta name="description" content="Gym Template">
    <meta name="keywords" content="Gym, unica, creative, html">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Hawary Trainer</title>
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'img/favicon.ico' %}">
    <!-- Google Font -->
    <link href="https://fonts.googleapis.com/css?family=Muli:300,400,500,600,700,800,900&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Oswald:300,400,500,600,700&display=swap" rel="stylesheet">

    <!-- Css Styles -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/flaticon.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/barfiller.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/slicknav.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css">
</head>

<body>
    <!-- Page Preloder -->
    <div id="preloder">
        <div class="loader"></div>
    </div>

    <!-- Offcanvas Menu Section Begin -->
    <div class="offcanvas-menu-overlay"></div>
    <div class="offcanvas-menu-wrapper">
        <div class="canvas-close">
            <i class="fa fa-close"></i>
        </div>
        <nav class="canvas-menu mobile-menu">
            <ul>
                <li><a href="{% url 'home'  %}">{% trans 'Home' %}</a></li>
                <li><a href="{% url 'about-us'  %}">{% trans 'About Us' %}</a></li>
                <li><a href="{% url 'transformation'  %}">{% trans 'Transformation' %}</a></li>
                <li><a href="{% url 'packages'  %}">{% trans 'Packages' %}</a></li>
                <li><a href="{% url 'contact'  %}">{% trans 'Contact' %}</a></li>
            </ul>
        </nav>
        <div id="mobile-menu-wrap"></div>
        <div class="canvas-social">
              <div>
                  <a href="{% url 'set_language' %}" class="frst-anc" >
                                        <span class="flex-en">
                                            <img  width="22px" height="22px" src="{% static 'img/american-2.png' %}" alt="">
                                        </span>
                                        English
                                      </a>
                  <a  href="{% url 'set_language' %}" class="scnd-anc">
                                        <span class="flex-en">
                                            <img width="22px" height="22px" src="{% static 'img/egypt.png' %}" alt="">
                                        </span>
                                           عربي
                                      </a>
            </div>
        </div>
    </div>
    <!-- Offcanvas Menu Section End -->
    <!-- Header Section Begin -->
    <header class="header-section">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-3">
                    <div class="logo">
                        <a href="{% url 'home'  %}">
                            <img src="{% static 'img/logo.png' %}"  alt="">
                        </a>
                    </div>
                </div>
                <div class="col-lg-6">
                                  <nav class="nav-menu">
                                        <ul>

                                            <li {% if request.get_full_path == "/" %}class="active"{% endif %}><a href="{% url 'home'  %}">{% trans 'Home' %}</a></li>
                                            <li {% if request.get_full_path == "/about-us/" %}class="active"{% endif %}><a href="{% url 'about-us'  %}">{% trans 'About Us' %}</a></li>
                                            <li {% if request.get_full_path == "/transformation/" %}class="active"{% endif %} ><a href="{% url 'transformation'  %}">{% trans 'Transformation' %}</a></li>
                                            <li {% if request.get_full_path == "/packages/" %}class="active"{% endif %} ><a href="{% url 'packages'  %}">{% trans 'Packages' %}</a></li>
                                            <li {% if request.get_full_path == "/contact/" %}class="active"{% endif %} ><a href="{% url 'contact'  %}">{% trans 'Contact' %}</a></li>
                                        </ul>
                                  </nav>
                         </div>
                <div class="col-lg-3">
                         <div class="top-option">
                              <div class="to-social">
                                  <div>
                                      <a href="{% url 'set_language' %}" class="frst-anc" >
                                        <span class="flex-en">
                                            <img  width="22px" height="22px" src="{% static 'img/american-2.png' %}" alt="">
                                        </span>
                                        English
                                      </a>
                                      <a href="{% url 'set_language' %}" class="scnd-anc">
                                        <span class="flex-en">
                                            <img width="22px" height="22px" src="{% static 'img/egypt.png' %}" alt="">
                                        </span>
                                           عربي
                                      </a>
                                    </div>
                              </div>
                         </div>
                </div>


                <div class="canvas-open">
                   <i class="fa fa-bars"></i>
                  </div>
            </div>

        </div>
    </header>
    <!-- Header End -->

  {% block content %} {% endblock %}


<!--    &lt;!&ndash; Get In Touch Section Begin &ndash;&gt;-->
<!--    <div class="gettouch-section">-->
<!--        <div class="container">-->
<!--            <div class="row">-->
<!--                <div class="col-md-4">-->
<!--                    <div class="gt-text">-->
<!--                        <i class="fa fa-map-marker"></i>-->
<!--                        <p>{{ setting.address }}</p>-->
<!--                    </div>-->
<!--                </div>-->
<!--                <div class="col-md-4">-->
<!--                    <div class="gt-text">-->
<!--                        <i class="fa fa-mobile"></i>-->
<!--                        <ul>-->
<!--                            <li>{{ setting.main_mobile_number }}</li>-->
<!--                            <li>{{ setting.secondary_mobile_number }}</li>-->
<!--                        </ul>-->
<!--                    </div>-->
<!--                </div>-->
<!--                <div class="col-md-4">-->
<!--                    <div class="gt-text email">-->
<!--                        <i class="fa fa-envelope"></i>-->
<!--                        <p>{{ setting.email }}</p>-->
<!--                    </div>-->
<!--                </div>-->
<!--            </div>-->
<!--        </div>-->
<!--    </div>-->
<!--    &lt;!&ndash; Get In Touch Section End &ndash;&gt;-->

    <!-- Footer Section Begin -->
    <section class="footer-section">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="contact-widget">
                        <div class="cw-text email to-social">
                            <a href="#"><img src="{% static 'img/social/whats.png' %}" style="width: 30px; height: 30px;"></a>
                        </div>
                        <div class="cw-text email to-social">
                            <a href="#"><img src="{% static 'img/social/gmail.png' %}" style="width: 30px; height: 30px;"></a>
                        </div>
                        <div class="cw-text email to-social">
                            <a href="#"><img src="{% static 'img/social/instagram.png' %}" style="width: 30px; height: 30px;"></a>
                        </div>
                        <div class="cw-text email to-social">
                            <a href="#"><img src="{% static 'img/social/tik3.png' %}" style="width: 30px; height: 30px;"></a>
                        </div>
                        <div class="cw-text email to-social">
                            <a href="#"><img src="{% static 'img/social/youtube.png' %}" style="width: 30px; height: 30px;"></a>
                        </div>
                        <div class="cw-text to-social">
                            <a href="#"><img src="{% static 'img/social/twitter.png' %}" style="width: 30px; height: 30px;"></a>
                        </div>
                        <div class="cw-text to-social">
                            <a href="#"><img src="{% static 'img/social/face.png' %}" style="width: 30px; height: 30px;"></a>
                        </div>

                    </div>
                </div>

            </div>

            <div class="row">
                <div class="col-lg-12 text-center">
                    <div class="copyright-text">
                        <p><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
  {% trans 'Copyright' %} &copy;<script>document.write(new Date().getFullYear());</script> {% trans 'All rights reserved' %}
  <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Footer Section End -->


    <!-- Js Plugins -->
    <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
    <script src="{% static 'js/masonry.pkgd.min.js' %}"></script>
    <script src="{% static 'js/jquery.barfiller.js' %}"></script>
    <script src="{% static 'js/jquery.slicknav.js' %}"></script>
    <script src="{% static 'js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>



</body>

</html>

templates/contact.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}

{% block content %}


    <!-- Contact Section Begin -->
    <section class="contact-section spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="head">
                        <h3>{% trans 'Contact Us Now' %}</h3>
                        <p>{% trans 'Be Your Best self' %}</p>
                    </div>

                </div>
            </div>
            <div class="row">
                <div class="col-lg-12">
                    <div class="leave-comment">
                        <form action="{% url 'contact'  %}" method="post">
                            {% csrf_token %}
                            <input required name="name" type="text" placeholder="{% trans 'Full Name' %}">
                            <input required name="email" type="email" placeholder="{% trans 'Email' %}">
                            <input required name="mobile" type="number" placeholder="{% trans 'Phone Number' %}">
                            <input required name="subject" type="text" placeholder="{% trans 'Subject' %}">
                            <textarea required name="comment" placeholder="{% trans 'Message' %}"></textarea>
                            <button type="submit">{% trans 'Submit' %}</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Contact Section End -->
{% endblock %}

templates/home.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}

  {% block content %}
    <!-- Hero Section Begin -->
    <section class="hero-section">
        <div class="hs-slider owl-carousel">
            {% for slider_img in setting.slider.all %}
            <div class="hs-item set-bg" data-setbg="{{ slider_img.img.url }}">
                <div class="container">
                    <div class="row">
                        <div class="col-lg-9 offset-lg-9">
                            <div class="hi-text">
                                {% get_current_language as LANGUAGE_CODE %}
                                {% if  LANGUAGE_CODE == 'ar'%}
                                <span>{{ slider_img.title_ar }}</span>
                                <h1>{{ slider_img.description_ar }}</h1>
                                {% else %}
                                <span>{{ slider_img.title }}</span>
                                <h1>{{ slider_img.description }}</h1>
                                {% endif %}
                                <!-- <a href="https://api.whatsapp.com/send?phone=201066243716" target="_blank" class="primary-btn">Join Us</a> -->
                                <a href="#" class="primary-btn pricing-btn">{% trans 'Subscribe now' %}</a>

                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </section>
    <!-- Hero Section End -->

    <!-- ChoseUs Section Begin -->
    <section class="choseus-section spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="section-title">
                        <span>{% trans 'Why choose online coaching with Hawary?' %}</span>
<!--                        <h2>PUSH YOUR LIMITS FORWARD</h2>-->
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-3 col-sm-6">
                    <div class="cs-item">
<!--                        <span class="flaticon-034-stationary-bike"></span>-->
                        <h4>{% trans 'Affordability' %}</h4>
                        <p>{% trans 'Online coaching with Hawary is considered a great option to get all the support you need if you aren’t quite in a position to hire a personal trainer. For instance, You will most likely get 16 weeks of online coaching with Hawary for the price of only 12 sessions/4 weeks with a personal trainer.' %}</p>
                    </div>
                </div>
                <div class="col-lg-3 col-sm-6">
                    <div class="cs-item">
<!--                        <span class="flaticon-033-juice"></span>-->
                        <h4>{% trans 'Service' %}</h4>
                        <p id="service-text" >{% trans "Coach Hawary has put a lot of time and effort to give his clients the best online coaching service and care. All programs are customized for you and your goal. Workout plans made to suit your level and goal All exercises are demonstrated in videos to make sure you are doing allot them  with  the right performance Sets, reps, tempo, and resting time are clarified in all exercises" %} <button id="show-btn">show more</button> </p>
                        <p id="more-p-hide"> {% trans "besides the coach’s notes on each workout Nutrition plans are so flexible and easy to follow, that’s because you have various food options to choose from, in other words, you will make your menu Your nutrition plan is 100% customized for you to suit your goal, lifestyle, and food preference. It includes your daily calorie intake, macronutrients, supplement guideline, and more of the essential elements to help you reach your goal." %}</p>
                    </div>
                </div>
                <div class="col-lg-3 col-sm-6">
                    <div class="cs-item">
<!--                        <span class="flaticon-002-dumbell"></span>-->
                        <h4>{% trans 'Follow-up' %}</h4>
                        <p>{% trans "Reaching your goal consists of many important factors but follow-up is our priority, Coach Hawary’s clients' service is available to help you answer your daily questions, in addition to checking your status, changing or adjusting any of your programs, or fulfilling your requirements in a regular basis." %}</p>
                    </div>
                </div>
                <div class="col-lg-3 col-sm-6">
                    <div class="cs-item">
<!--                        <span class="flaticon-014-heart-beat"></span>-->
                        <h4>{% trans 'Results' %}</h4>
                        <p>{% trans "Coach Hawary's favorite saying is Trust the process Since 2015 he has worked with over 6000+ clients as their personal trainer or an online coach. Results are guaranteed with coach Hawary as he works with each client’s case as if it’s the only one he has and the results are always Phenomenal, not only great body transformations but also changing whole lifestyles." %}</p>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- ChoseUs Section End -->

    <!-- Banner Section Begin -->
    <section class="banner-section set-bg" data-setbg="{% static 'img/banner-bg.jpg' %}">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <div class="bs-text service-banner">
                        <h2>{% trans 'Exercise until the body obeys.' %}</h2>
                        <div class="bt-tips">{% trans 'Where health, beauty and fitness meet.' %}</div>
                        <a href="https://www.youtube.com/watch?v=EzKkl64rRbM" class="play-btn video-popup"><i
                                class="fa fa-caret-right"></i></a>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Banner Section End -->

    <!-- Team Section Begin -->
     <section class="team-section spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="section-title">
                        <span>{% trans 'Packages' %}</span>
                        <h2>{% trans 'Choose your plan' %}</h2>
                    </div>
                </div>
            </div>
            <div class="row team">
                <div class="ts-slider owl-carousel">
                    {% for group in packages_group %}
                    <div class="col-lg-4">
                        <div class="ts-item set-bg center-mid-pic" data-setbg="{{ group.img.url }}">
                            <div class="ts_text">
                                {% get_current_language as LANGUAGE_CODE %}
                                {% if  LANGUAGE_CODE == 'ar'%}
                                <h4>{{ group.name_ar }}</h4>
                                <span>{{ group.description_ar }}</span>
                                {% else %}
                                <h4>{{ group.name }}</h4>
                                <span>{{ group.description }}</span>
                                {% endif %}
                                <a href="{% url 'packages'  %}" class="primary-btn pricing-btn">{% trans 'Enroll now' %}</a>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </section>
    <!-- Team Section End -->
    {% include "includes/clients-opinion.html" %}

{% endblock %}

templates/packages.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}

{% block content %}
    <!-- Breadcrumb Section Begin -->
    <section class="breadcrumb-section set-bg" data-setbg="{% static 'img/breadcrumb-bg.jpg' %}">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <div class="breadcrumb-text">
<!--                        <h2>Packages</h2>-->
                        <div class="bt-option">
<!--                            <a href="{% url 'home'  %}">Home</a>-->
                            <span>{% trans 'Packages' %}</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Breadcrumb Section End -->

    {% for group in groups %}
        {% if group.package_set.count > 0%}
        <!-- Pricing Section Begin -->
        <section  class="pricing-section service-pricing spad">
            <div id="first-plan" class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="section-title">
                            {% get_current_language as LANGUAGE_CODE %}
                            {% if  LANGUAGE_CODE == 'ar'%}
                            <span>{{ group.name_ar }}</span>
                            {% else %}
                            <span>{{ group.name }}</span>
                            {% endif %}
                            <h2>{% trans 'Choose your pricing plan' %}</h2>
                        </div>
                    </div>
                </div>
                <div class="row justify-content-center">
                    {% for package in group.package_set.all %}
                    <div class="col-lg-4 col-md-8">
                        <div class="ps-item">
                            {% if  LANGUAGE_CODE == 'ar'%}
                            <h3>{{ package.name_ar }}</h3>
                            {% else %}
                            <h3>{{ package.name }}</h3>
                            {% endif %}
                            <div class="pi-price">
                                {% if  LANGUAGE_CODE == 'ar'%}
                                <h2>{% trans 'LE' %} {{ package.price_ar }}</h2>
                                {% else %}
                                <h2>LE {{ package.price }}</h2>
                                {% endif %}
                            </div>
                            <ul>
                                {% for details in package.package_details.all %}
                                {% if  LANGUAGE_CODE == 'ar'%}
                                <li>{{ details.description_ar }}</li>
                                {% else %}
                                <li>{{ details.description }}</li>
                                {% endif %}
                                {% endfor %}
                            </ul>
                            <a href="#" class="primary-btn pricing-btn">{% trans 'Enroll now' %}</a>
                            <!-- <a href="#" class="thumb-icon"><i class="fa fa-picture-o"></i></a> -->
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </section>
        <!-- Pricing Section End -->
        {% endif %}
    {% endfor %}

{% endblock %}